
GET localhost:7000/api/hotel

###

// GET ALL ROOMS FOR HOTEL
GET localhost:7000/api/hotel/2/rooms

###


###

POST localhost:7000/api/hotel/
Content-Type: application/json

{
  "name": "Hotel New York",
  "address": "Plaza 1200 St",
  "rooms": [
    {
      "number": "202",
      "price": 100
    },
    {
      "number": "322",
      "price": 211
    }
  ]
}

###

// UPDATE HOTEL
PUT localhost:7000/api/hotel/2
Cootent-Type: "application/json"

{
    "id": 1,
    "name": "Updated Hotel Name",
    "address": "Updated Address",
    "rooms": [
        {
            "id": 101,
            "number": 1,
            "price": 100
        },
        {
            "id": 102,
            "number": 2,
            "price": 150
        }
    ]
}

###

//

###

//