
// get all hotels
GET localhost:7000/api/hotel

###
// get hotel by id
GET localhost:7000/api/hotel/3


###

// get all rooms for hotels
GET localhost:7000/api/hotel/2/rooms

###

// delete hotel

###

// create new hotel
POST localhost:7000/api/hotel/
Content-Type: application/json

{
  "name": "Hotel New York",
  "address": "Plaza 1200 St",
  "rooms": [
    {
      "number": "202",
      "price": 100
    },
    {
      "number": "322",
      "price": 211
    }
  ]
}

###

// UPDATE HOTEL
PUT localhost:7000/api/hotel/2
Cootent-Type: application/json

{
    "id": 1,
    "name": "Updated Hotel Name",
    "address": "Updated Address",
    "rooms": [
        {
            "id": 101,
            "number": 1,
            "price": 100
        },
        {
            "id": 102,
            "number": 2,
            "price": 150
        }
    ]
}

###

// delete hotel
DELETE localhost:7000/api/hotel/1

###

POST localhost:7000/auth/register
Content-Type: application/json

{
  "username": "user1",
  "password": "1234"
}

###

POST http://localhost:7000/api/auth/register
Content-Type: "application/json"

{
"username":"user6",
"password":"p1234"
}

###
POST http://localhost:7000/api/auth/login
Content-Type: "application/json"

{
"username":"user6",
"password":"p1234"
}

###
GET http://localhost:7000/api/secured/demo
Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIklkcmlzIElzY2lcIiIsInN1YiI6InVzZXI2IiwiZXhwIjoxNzQxOTQ0MjE5LCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXI2In0.kMAj56olnoGmXkOHOZG-0HY64HL2yhKNyz86QEBR758

